### ISSUE TITLE
PHP 8 compatibility issue

### ISSUE THREAD

**Issue by wu-edward** [acquia/blt-launcher#7]
Looks like the BLT launcher has the same issue the Drush launcher had with `padraic/phar-updater` being abandoned and not compatible with PHP 8: https://github.com/drush-ops/drush-launcher/issues/84. This is preventing the BLT launcher from being run on any envs with PHP 8.

Seeing this issue trying to run blt on PHP 8:
```
Box Requirements Checker
========================

> Using PHP 8.0.8
> PHP is using the following php.ini file:
  /usr/local/php8.0/etc/cli/php.ini

> Checking Box requirements:
  ..E.........

                                                                                
 [ERROR] Your system is not ready to run the application.                       
                                                                                

Fix the following mandatory requirements:
=========================================

 * The package "padraic/humbug_get_contents" requires the version "^5.3 || ^7.0
   || ^7.1 || ^7.2" or greater.
```

**Comment by danepowell** [comment]
Thanks, looks like the fix is here: https://github.com/drush-ops/drush-launcher/commit/3ae600ef43b2ea68836c6050c71f7af5cc7df8ee

I created an internal ticket to track. Hopefully it's as easy as swapping the vendor.
